### ISSUE TITLE
Adjust emoji's image size

### ISSUE THREAD

**Issue by tokitou-san** [UziTech/marked-emoji#112]
Heyo!
After parsing: emoji size looks off, and I'm using emoji's image instead unicode.
```js
    const emoji_options: MarkedEmojiOptions = {
        emojis,
        unicode: false
    };
```
input: `:+1:`
output:
![Screenshot from 2023-07-17 21-40-06](https://github.com/UziTech/marked-emoji/assets/114811070/92c8af3d-4028-4eac-b53a-4ef8a0d35cbf)
and with input like this:
`:+1: Breaks`
output:
![Screenshot from 2023-07-17 21-46-59](https://github.com/UziTech/marked-emoji/assets/114811070/2f2fb569-da31-4799-9882-5778393ac8ee)
see? image needs `w-x inline-flex` something like this ig.
It would be great if we can adjust emoji size without affecting external images while parsing.

**Comment by baseplate-admin** [comment]
This can be better achieved if you can let the developers add custom class to emojis :D

**Comment by UziTech** [comment]
You can change the renderer if you want custom html

```js
const emojiExtension = markedEmoji({
  emojis,
  unicode: false,
});

const emojiRenderer = emojiExtension.extensions[1].renderer;
emojiExtension.extensions[1].renderer = (token) {
  const html = emojiRenderer(token);
  return html.replace(/^<img /, '<img width="x" height="y" ');
}

marked.use(emojiExtension);

```

**Comment by baseplate-admin** [comment]
This sounds a bit hacky, can't we do something like 

```typescript
const emojiExtension = markedEmoji({
  emojis,
  class:'marked-emoji',
  unicode: false,
});
```

**Comment by UziTech** [comment]
You can create an extension that does that. I like to keep my extensions simple with the least amount of options necessary.

Overriding an extension renderer is not a hack. marked made it specifically so you can override renderers and tokenizers.

If you don't like the replace you can return the html however you want.

```js
marked.use(markedEmoji({
  emojis,
  unicode: false,
}));

marked.use({
  extensions: [{
    name: "emoji",
    renderer(token) {
        return `<img class="marked-emoji" alt="${token.name}" src="${token.emoji}">`;
    }
  }]
}
```

**Comment by baseplate-admin** [comment]
Fair enough. Thanks for your explanation

**Comment by baseplate-admin** [comment]
Hey @UziTech, Sorry to ping you but can you show me a way to override emoji using `Marked` constructor?

```typescript
  const marked = new Marked(
        
        // Emoji plugin
        markedEmoji({
            emojis,
            unicode: false
        }),
        {
            // We dont need github like header prefix
            headerIds: false
        }
    );

 marked.use({
        extensions: [
            {
                name: "emoji",
                renderer: (token) => {
                    return `<img class="inline-flex" alt="${token.name}" src="${token.emoji}">`;
                }
            }
        ]
    });

```


This is not producing the desired output?

**Comment by UziTech** [comment]
That works for me. What is is producing and what is the desired output?

The objects passed to the `Marked` constructor are extensions passed to `use` internally. So the following code would be the same:

```js
const marked = new Marked(

  // Emoji plugin
  markedEmoji({
    emojis,
    unicode: false
  }),

  // Override emoji renderer
  {
    extensions: [
      {
        name: 'emoji',
        renderer: (token) => {
          return `<img class="inline-flex" alt="${token.name}" src="${token.emoji}">`;
        }
      }
    ]
  },

  // Other options
  {
    // We dont need github like header prefix
    headerIds: false
  }
);
```

**Comment by baseplate-admin** [comment]
I did something along the lines of this 

```typescript
const marked = new Marked({
 markedEmoji(emoji_options),
        {
            name: "emoji",
            renderer: (token) => {
                return `<img class="inline-flex" alt="${token.name}" src="${token.emoji}">`;
            }
        },

})
```


Nvm. Should i add this to the `readme,md` ? For future developers stumbling on this error?

**Comment by UziTech** [comment]
This override behavior is documented on marked https://marked.js.org/using_pro#extensions. It could be more prominent if you want to add an example in the marked documentation.
